variable "region" { default = "ap-south-1" }
variable "vpc_name" { default = "fast-translit-vpc" }
variable "vpc_cidr" { default = "10.0.0.0/16" }
variable "azs" { default = ["ap-south-1a", "ap-south-1b", "ap-south-1c"] }
variable "private_subnets" { default = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"] }
variable "public_subnets" { default = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"] }
variable "cluster_name" { default = "fast-translit-cluster" }
variable "cluster_version" { default = "1.30" }
variable "instance_types" { default = ["t3.medium"] }
variable "min_size" { default = 1 }
variable "max_size" { default = 3 }
variable "desired_size" { default = 2 }
